### ISSUE TITLE
Regarding CV1.txt and CV2.txt

### ISSUE THREAD

**Issue by jasvinderk** [sulfierry/free_energy_landscape#3]
Hello

Thank you for the resource!
I am using gromacs, I dont see any files named CV1 and CV2.txt.

How can I generate these, please help!

P.S. I am new to Bioinformatics

**Comment by jasvinderk** [comment]
I tried to create these files using the following commands:
# For distance
gmx_remd distance -s topol.tpr -f md_0_1_noPBC_center.xtc -n index.ndx -oall distance.xvg
(selected protein for both)

# For angles
gmx_remd angle -f md_0_1_noPBC_center.xtc -n index.ndx -type dihedral -od angle.xvg
(selected protein)

angle.xvg – CV1
distance.xvg – CV2

awk '$1 ~ /^[0-9]/ {print $0}' angle.xvg > cv1.txt
awk '$1 ~ /^[0-9]/ {print $0}' distance.xvg > cv2.txt

But after running this command: 
free_energy_landscape cv1.txt cv2.txt --names "CV1 (Angle)" "CV2 (Distance)" --energy 3.0 --discretize 1.0

I get the following error:
Loading data...

Data loaded successfully!
CV1: cv1.txt, CV2: cv2.txt

Plotting free energy profiles...

Plotting histograms...

Plotting Collective variables normalized by frame...

An unexpected error occurred: x and y must have same first dimension, but have shapes (181,) and (25001,)

and it stops there....extracting data out of PC1.xvg and PC2. xvg did not work either.

Anything that can be done?

**Comment by sulfierry** [comment]
Hi @jasvinderk,

The issue you're experiencing is due to a mismatch in the number of data points between your angle and distance files. This discrepancy prevents the free energy landscape algorithm from running correctly because it requires both input files to have the same number of data points.

### Analyzing Your Commands

#### For Distance:

```sh
gmx_remd distance -s topol.tpr -f md_0_1_noPBC_center.xtc -n index.ndx -oall distance.xvg
```

This command is correct for calculating distances between groups of atoms specified in the index file.

#### For Angles:

```sh
gmx_remd angle -f md_0_1_noPBC_center.xtc -n index.ndx -type dihedral -od angle.xvg
```

This command is correct for calculating dihedral angles.

### Problem

The error message "An unexpected error occurred: x and y must have same first dimension, but have shapes (181,) and (25001,)" indicates that `angle.xvg` and `distance.xvg` have different numbers of frames (181 and 25001, respectively).

### Solution

1. **Ensure Consistency in Trajectory Processing**:
   - Make sure you are using the same trajectory file (`md_0_1_noPBC_center.xtc`) for both commands.

2. **Check and Modify the Index File**:
   - Verify that the `index.ndx` file is correctly referencing the same group of atoms for both calculations.

3. **Re-run the Commands Consistently**:

#### For Angles:

```sh
gmx angle -f md_0_1_noPBC_center.xtc -s topol.tpr -n index.ndx -type dihedral -od angle.xvg
```

#### For Distance:

```sh
gmx distance -f md_0_1_noPBC_center.xtc -s topol.tpr -n index.ndx -oall distance.xvg
```

4. **Verify the Output Files**:

Ensure that both `angle.xvg` and `distance.xvg` have the same number of data points. You can check this by counting the lines in each file:

```sh
wc -l angle.xvg distance.xvg
```

Both files should have the same number of lines.

5. **Extract Data for Free Energy Landscape**:

```sh
awk '$1 ~ /^[0-9]/ {print $0}' angle.xvg > cv1.txt
awk '$1 ~ /^[0-9]/ {print $0}' distance.xvg > cv2.txt
```


### Final Check

Ensure that `cv1.txt` and `cv2.txt` have the same number of lines: Both files should match in line count.


```sh
wc -l cv1.txt cv2.txt
```

6. **Run the Free Energy Landscape Analysis**:

```sh
free_energy_landscape cv1.txt cv2.txt --names "CV1 (Angle)" "CV2 (Distance)" --energy 3.0 --discretize 1.0
```

If the problem persists, please provide more details about the pre-processing steps or any other commands you used, and I'll be happy to assist further.

**Comment by sulfierry** [comment]
@jasvinderk  if you have no further questions about this topic, I will close the issue or if you have any questions, I will be at your disposal.

**Comment by jasvinderk** [comment]
Yes ill get back to you! Thank you so much for your response :)
